---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "commonMeta" . | indent 4 }}
    component: {{ template "fullname" . }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: {{ .Values.strategyType }}
  selector:
    matchLabels:
      component: {{ template "fullname" . }}
      role: controller
  template:
    metadata:
      labels:
        {{- include "commonMeta" . | indent 8 }}
        component: {{ template "fullname" . }}
        role: controller
    spec:
      serviceAccount: {{ .Chart.Name }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.repository }}:{{ .Values.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.awsKey }}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.awsSecret }}
            - name: AWS_DEFAULT_REGION
              value: {{ .Values.awsRegion }}
            {{- if .Values.awsHttpsProxy }}
            - name: AWS_HTTPS_PROXY
              value: {{ .Values.awsHttpsProxy }}
            {{- end }}
            - name: ECR_RESYNC_PERIOD
              value: {{ .Values.ecrResyncPeriod }}
            - name: ECR_SECRET_NAME
              value: {{ .Values.ecrSecretName }}
            - name: KUBE_CONFIG_TYPE
              value: {{ default "in" .Values.kubeConfigType }}
            - name: KUBE_CONFIG_PATH
              {{- if .Values.kubeConfigFilePath }}
              value: "/kube/config"
              {{- else }
              value: 
              {{- end }}
            - name: WORKER_NUMBER
              value: {{ .Values.workerNumber }}
            - name: EXCLUDE_NAMESPACES
              value: {{ .Values.exclude | quote }}
      {{- if .Values.kubeConfigFilePath }}
          volumeMounts:
            - mountPath: /kube/config
              name: kube-config
      volumes:
      - name: kube-config
        hostPath:
          path: {{ .Values.kubeConfigFilePath }}
          type: File
      {{- end }}
